apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-docker
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-docker
  template:
    metadata:
      labels:
        app: sample-docker
    spec:
      containers:
      - name: app
        image: a2mo/sample-docker-project
