apiVersion: v1
kind: Service
metadata:
  name: sample-docker-service
  namespace: test
spec:
  selector:
    app: sample-docker
    version: v1
  type: NodePort
  ports:
    - name: default-port
      port: 80
      targetPort: web
      protocol: TCP
      nodePort: 30300

