management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      group:
        liveness:
          include: livenessState, ping, refreshScope
        readiness:
          include: readinessState, db, diskSpace
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
